### ISSUE TITLE
Myra the Magnificent

### ISSUE THREAD

**Issue by Fryyyyy** [Fryyyyy/Fryatog#200]
She no come up

**Comment by lunakv** [comment]
This is an issue with all eternal legal cards from Unfinity. They have `set_type` equal to "funny", so they get classified as uncards, but they don't actually match is:funny or border:silver, so the uncard query can't get them either. That leaves them unavailable for both regular and uncard searches.

We should fix the uncard classifier to match exactly what the uncard query is actually searching for (and update both to a post-UNF reality). We could also have a discussion on how needed this separation of uncards actually is while we're at it.

**Comment by Fryyyyy** [comment]
+100 agree

Also grats on our 200th issue!

**Comment by lunakv** [comment]
I think I actually came up with a pretty solid heuristic for what counts as a "dumb card", namely something that's Not Legal (that is, it isn't legal, banned, or restricted) in vintage. Given that vintage is basically a format of "anything goes", this criterion alone catches all the normal silver border / acorn stuff as well as all the Planes, Schemes, holiday promos, weird gold-border WC cards etc. It also means that the actual "dumb card" query string can stay basically the same, since all the options it searches for are definitionally not vintage legal.

The only corner case here is that during preview season, where new cards aren't legal anywhere until their release date. This means we'd have to explicitly consider as of yet unreleased cards to not be dumb, but since that's the time when people are most likely to ask about those cards anyway, I think I'm happy letting them slip through as false negatives during that time period. 

In addition to being a fairly simple filter that hopefully won't need that much updating whenever WotC decides on a new thing to print, it also catches a bunch of stuff that the old filter did not, such as `!acorn stash`, which happily returns as a normal card now even though it probably shouldn't.

> Also grats on our 200th issue!

Hurray for imperfect software! :partying_face: Congrats :slightly_smiling_face:

**Comment by Fryyyyy** [comment]
`This means we'd have to explicitly consider as of yet unreleased cards to not be dumb`

Is this easily expressible in logic?

**Comment by lunakv** [comment]
I believe so. Scryfall's card objects have a release date property, so as long as we can tell the current time, it's just a simple comparison.

**Comment by lunakv** [comment]
(plus another check on whether something is its first printing—unreleased reprints don't have to be accounted for—but the card object also has a flag indicating whether a card is a reprint or not)
