### ISSUE TITLE
Implement advanced search

### ISSUE THREAD

**Issue by Fryyyyy** [Fryyyyy/Fryatog#7]
Straight into the Scryfall API

**Comment by Villawhatever** [comment]
Been doing some thinking on this. Since we don't want to save state, maybe just return a list that's like

Card A * Card B * Card C * Card D

Cap at two full messages, and append "(and $NUMBER more. Try refining your search)" if it's larger than that. If it's _wildly_ larger, just return "$NUMBER results. Try refining your search" from the outset.
Thoughts?

**Comment by Fryyyyy** [comment]
Meaning just card names ?

**Comment by Villawhatever** [comment]
Yeah, unless it's already a unique match, in which case just return the card's info like we normally word for !card $NAME

**Comment by Fryyyyy** [comment]
Fixed in 9e5a815168335c8e72531acd0a9e9a1aa51bc1aa  - probs needs some tweaks in the future
